--CRIA UM LOGIN DE USUARIO
CREATE LOGIN henrique WITH PASSWORD = '12345';

--CRIA UM USUARIO DENTRO DE UM BANCO DE DADOS
CREATE USER henrique FOR LOGIN henrique;

--COMANDO DENY -- BLOQUEIA O ACESSO
DENY INSERT, UPDATE, DELETE
TO henrique;

--COMANDO REVOKE - REVERTE A PERMISSÃO DO USÚARIO
REVOKE INSERT, UPDATE, DELETE
TO henrique;